Update core to 0.11.0
membraneframework/membrane_flac_plugin pull request #17
Opened 2022-11-18 12:12 UTC by Rados13

2022-11-21 14:08 UTC, LVala requested changes
- Remove `type` and add `spec` to `def_options`
- Bump versions in `README.md` and `mix.ex` in order to release it

2022-11-21 14:08 UTC, LVala commented on test/membrane_flac_plugin/integration_test.exs
> +             ParsingPipeline.make_pipeline(in_path, out_path, streaming?)
Is there some kind of need to reference the module inside of itself?

2022-11-21 14:08 UTC, LVala commented on test/membrane_flac_plugin/integration_test.exs
> +             ParsingPipeline.make_pipeline(in_path, out_path, streaming?)
```suggestion
             make_pipeline(in_path, out_path, streaming?)
```

2022-11-22 10:51 UTC, Rados13 commented on test/membrane_flac_plugin/integration_test.exs
> +             ParsingPipeline.make_pipeline(in_path, out_path, streaming?)
Here we are inside module `IntegrationTest` and module `ParsingPipeline` is above `IntegrationTest`(We have two modules inside one file).

2022-11-22 12:41 UTC, LVala approved these changes

2022-11-23 08:46 UTC, merged